#!/bin/bash
# 
# Chooses between 64 and 64 prefixes and execute wine accordingly 
# This tool expects wine from winehq repositories
#
# snortt@gmail.com
# Sat Aug 10 17:03:02 EDT 2019
# 

# This will handle bad and ugly names
IFS="
"

if [ "$#" -lt "1" ]; then
    echo -e "Usage: $(basename $0) <action> [opt]"
    echo -e "  actions: winecfg, wineboot, wineconsole, winetricks"
    echo -e "  options: regular options you would pass to any action"
    echo -e "  IF no action is given, regular wine command will be invoked with given opts"
    exit 201
fi

# wine staging is in /opt/wine-staging
PATH="/bin:usr/bin:/opt/wine-staging/bin/:~/bin/"
WINE64HOME="/home/gabriel/.wine64"

case "$1" in
    "winecfg")
        shift
        WINEARCH=win64 WINEPREFIX=${WINE64HOME} winecfg $@
        ;;
    "wineboot")
        shift
        WINEARCH=win64 WINEPREFIX=${WINE64HOME} wineboot $@
        ;;
    "wineconsole")
        shift
        WINEARCH=win64 WINEPREFIX=${WINE64HOME} wineconsole $@
        ;;
    "winetricks")
        shift
        WINEARCH=win64 WINEPREFIX=${WINE64HOME} winetricks $@
        ;;
    *)
        WINEARCH=win64 WINEPREFIX=${WINE64HOME} wine $@
        ;;
esac


